# Generated by Django 3.2.7 on 2021-10-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(default='', max_length=50, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
